name: Deploy Mezon FE Prod
on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: mezone-fe-dev
    name: Build Mezon FE
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo "Environments"
          echo "NODE_ENV: ${{ env.NODE_ENV }}"
          echo "Node version: $(node -v)"
          echo "Installing dependencies"
          source ~/.bashrc
          yarn

      - name: Build
        run: |
          echo "Build"
          rm apps/chat/.env
          mv apps/chat/prod.env apps/chat/.env
          yarn build:chat
      - name: Compress build artifact
        run: |
          echo "Compress Artifact"
          cd ./dist/apps/chat/
          zip -r mezon-fe-prod.zip *
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mezon-fe-prod
          path: ./dist/apps/chat/mezon-fe-prod.zip
          retention-days: 1

  deploy:
    runs-on: mezon-fe-prod
    name: Deploy Mezon FE
    environment: prod
    needs:
      - build
    steps:
      - name: Clear www folder
        run: |
          echo "Clearing /var/www/mezon-fe/"
          rm -rf /var/www/mezon-fe/*

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: mezon-fe-prod
          path: /var/www/mezon-fe/
        
      - name: Extract and check files
        run: |
          cd /var/www/mezon-fe/
          ls -la
          unzip mezon-fe-prod.zip

